eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:20001/eureka/   #注册中心地址

spring:
  application:
    name: licensingservice
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true
#      discovery:
#        enabled: true
#        serviceId: configserver
server:
  port: 8088

feign:
  hystrix:
    enabled:  true
